### ISSUE TITLE
How to handle if user says answer?

### ISSUE THREAD

**Issue by sharanken** [alexa/skill-sample-nodejs-trivia#105]
My problem is when the user says answer instead of option number, how can we handle that. And how can we take any type of user input, and return back by saying to select only options?

**Comment by aszk** [comment]
You can add slots to answerIntent, and sample phrases to get users utterance other than numbers when they say actual answer instead of number. For example, adding AMAZON.color to get color, etc. However in this case, you might have to have many slots and sample phrases it depends on what answer you expect, in addition, your code needs to handle those slots values. This repository might be good to understand. https://github.com/alexa-samples/skill-sample-nodejs-quiz-game
