### ISSUE TITLE
Answers not displaying correctly

### ISSUE THREAD

**Issue by natemunk** [alexa/skill-sample-nodejs-trivia#20]
Here are some example answers, ignore the spelling haha. If you look further down you can see the response given once the skill is started. The answers just seem to be random letters. Not sure what to make of it. Any ideas?

{
            "Hint Endure to the end.": [
                    "first knee fi three seven",
                    "second knee fi two twenty five",
                    "second knee fi two twenty seven",
                    "second knee fi nine verses twenty eight and twenty nine",
                    "second knee fi twenty five verses twenty three and twenty six",
                    "second knee fi twenty seven verses seven through nine"
            ]
        }

"ssml": "<speak> Welcome to Scripture Mastery. I will ask you 1 questions, try to get as many right as you can. Just say the number of the answer. Let's begin. Question 1. Hint Endure to the end. **1. E. 2. U. 3. Q. 4. S.**  </speak>"

**Comment by natemunk** [comment]
Found out the problem, errors created by using periods in the questions.. Even though it says to use periods or question marks in the comments..

**Comment by jamesylgan** [comment]
Any workaround?

**Comment by natemunk** [comment]
Just changing the periods to question marks fixed it for me.. you having the same issue?

**Comment by jamesylgan** [comment]
I was hoping to figure out a way to include their periods. I tried escaping them to no avail.

**Comment by natemunk** [comment]
There might be a way to set a character other than the period to separate the values.

**Comment by dwds** [comment]
I tried to debug this for hours and could not figure out where the problem is occurring. I had to workaround it by removing all periods from my question text (including abbreviations and end-of-sentence periods). I would like a solution that actually allows you to have periods. Also, I don't think the letters it says are random. 'Q' 'U' 'E' 'S' ... Notice a pattern? Somehow the string "QUESTION" is getting split into the first four letters, and those are being used as the answer choices. But I can't for the life of me figure out how or why that is happening.
